language: java
sudo: false
jobs:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: openjdk9
    - os: osx
      jdk: openjdk10
    - os: osx
      jdk: openjdk11

script: mvn clean install
